[package]
name = "argyph-embed"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
unwrap_used = "deny"
expect_used = "warn"

[dependencies]
thiserror.workspace = true

[lib]
name = "argyph_embed"
path = "src/lib.rs"
