[package]
name = "argyph-fs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
camino = "1"
blake3 = { version = "1", features = ["rayon"] }
ignore = "0.4"
rayon = "1"

[lib]
name = "argyph_fs"
path = "src/lib.rs"
