[package]
name = "argyph-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
argyph-core = { path = "../argyph-core" }
argyph-mcp = { path = "../argyph-mcp" }
thiserror.workspace = true
clap = { version = "4", features = ["derive"] }
camino = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1"

[lib]
name = "argyph_cli"
path = "src/lib.rs"
